apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mgmul34tb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mgmul34tb-nodejs 
  name: mgmul34tb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mgmul34tb-nodejs 
